//
//  photosPresenter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class photosPresenter: photosPresenterProtocol, photosInteractorOutputProtocol {
    func configureCell(cell: PhotoCellViewProtocol, indexPath: IndexPath) {
        let photo = allItems[indexPath.row]

        cell.configure(photos: photo)
        //view?.reloadData()
    }
    
   var numberOfRows: Int {
        return allItems.count
    }
    
    
    
    
    private var allItems : [Photo] = [Photo]()
    
    
    func getDataSucssesfully(photos: [Photo]) {
        print(photos.count)
        self.allItems = photos
        view?.reloadData()
    }
    
    func faildToGetData(error: Error) {
        print(error)
    }
    
    func getPhotos(searchType: SearchingType) {
        
        interactor?.getPhotos(searchType: searchType)
    }
    
    
    
    

    weak private var view: photosViewProtocol?
    var interactor: photosInteractorInputProtocol?
    private let router: photosWireframeProtocol

    init(interface: photosViewProtocol, interactor: photosInteractorInputProtocol?, router: photosWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
