//
//  photosInteractor.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class photosInteractor: photosInteractorInputProtocol {
    
    var networkManger:FlickerAPI? = nil
    func getPhotos(searchType: SearchingType) {
        
        networkManger?.requestFor(searchType: searchType, with: 1, decode: { json -> Photos? in
            guard let flickerResult = json as? Photos else { return  nil }
            return flickerResult
        }) { [unowned self] result in
            DispatchQueue.main.async {
                
                switch result{
                case .success(let value):
                  // print(value)
//                    photos(value.photos.photo)
                    self.presenter?.getDataSucssesfully(photos: value.photos.photo)
                    
                case .failure(let error):
                    print(error.debugDescription)
                    guard self.networkManger?.requestCancelStatus == false else { return }
                    
                    self.presenter?.faildToGetData(error: error!)
                }
            }
    
    }
    }
    

    weak var presenter: photosInteractorOutputProtocol?
}


       

   
