//
//  registerProtocols.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol registerWireframeProtocol: class {
func showHomeScreen()
}
//MARK: Presenter -
protocol registerPresenterProtocol: class {

    var interactor: registerInteractorInputProtocol? { get set }
    func handeRegister(email: String, password: String, username:String)
}

//MARK: Interactor -
protocol registerInteractorOutputProtocol: class {
    func regiterDoneSuccessfully()
    func registerFaild(error:Error)

    /* Interactor -> Presenter */
}

protocol registerInteractorInputProtocol: class {

    func handleRegister(email:String , password:String , username:String)
    var presenter: registerInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol registerViewProtocol: class {

    func showIndicator()
    func hideIndicator()
    func showErrorAlert(error:String)
    var presenter: registerPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
