//
//  registerPresenter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class registerPresenter: registerPresenterProtocol, registerInteractorOutputProtocol {
  

    weak private var view: registerViewProtocol?
    var interactor: registerInteractorInputProtocol?
    private let router: registerWireframeProtocol

    init(interface: registerViewProtocol, interactor: registerInteractorInputProtocol?, router: registerWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    
    func regiterDoneSuccessfully() {
         view?.hideIndicator()
          router.showHomeScreen()
          
      }
      
      func registerFaild(error: Error) {
         view?.hideIndicator()
          view?.showErrorAlert(error: error.localizedDescription)
      }
      
      func handeRegister(email: String, password: String, username:String) {
        view?.showIndicator()
        interactor?.handleRegister(email: email, password: password ,username:username )
      }
      

}

