//
//  registerRouter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class registerRouter: registerWireframeProtocol {
    
    
private weak var navigationController: UINavigationController?
    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
       
        let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "\(registerViewController.self)") as! registerViewController
        let interactor = registerInteractor()
        let router = registerRouter()
        let presenter = registerPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
      


        return view
    }
    
    
    func showHomeScreen() {
        let vc = homeRouter.createModule()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}

