//
//  registerViewController.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

import AnAlertView

class registerViewController: UIViewController, registerViewProtocol  , AlertViewDelegate{
     @IBOutlet weak var profileImageView: UIImageView!
    @IBOutlet weak var email: DesignableUITextField!
    @IBOutlet weak var userName: DesignableUITextField!
    
    @IBOutlet weak var password: DesignableUITextField!
    @IBOutlet weak var repeatedPassword: DesignableUITextField!
    @IBAction func backButtonPressed(_ sender: Any) {
        
        navigationController?.popViewController(animated: true)
    }
    @IBAction func addPhotoButton(_ sender: Any) {
        handleSelectProfileImageView()
    }
    func dismissButtonTapped(_ button: UIButton) {
        email.text = ""
        password.text = ""
        repeatedPassword.text = ""
    }
    
    func showIndicator() {
        showActivityIndicator()
    }
    
    func hideIndicator() {
        hideActivityIndicator()
    }
    
    func showErrorAlert(error: String) {
        AlertView.showAlert(message: error, button: "ok", delegate: self, container: self, image: UIImage(named: "warning"))
    }
    
    
    var presenter: registerPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let customColor = UIColor.white
        
        //                username.setRightPaddingPoints(-20)
        //                password.setLeftPaddingPoints(10)
        
        email.layer.borderColor = customColor.cgColor
        userName.layer.borderColor = customColor.cgColor
        password.layer.borderColor = customColor.cgColor
        repeatedPassword.layer.borderColor = customColor.cgColor
        
        email.layer.borderWidth = 1.0
        userName.layer.borderWidth = 1.0
        
        password.layer.borderWidth = 1.0
        repeatedPassword.layer.borderWidth = 1.0
        repeatedPassword.layer.borderWidth = 1.0
    }
    
    @IBAction func signUpBtn(_ sender: Any) {
        
        if userName.text == "" {
            AlertView.showAlert(message: "make username", button: "ok", delegate: self, container: self, image: UIImage(named: "warning"))
        }
        
        if password.text == repeatedPassword.text {
            presenter?.handeRegister(email: email.text!, password: password.text! , username:userName.text!)
        }
            
        
        else {
            AlertView.showAlert(message: "Password Dosn't Match", button: "ok", delegate: self, container: self, image: UIImage(named: "warning"))
        }
    }
    
}
