//
//  registerInteractor.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import FirebaseAuth
import Firebase
import FirebaseDatabase


class registerInteractor: registerInteractorInputProtocol {
    
    var ref: DatabaseReference!
    func handleRegister(email: String, password: String, username: String){
        ref = Database.database().reference()
        Auth.auth().createUser(withEmail: email, password: password) {[weak self] (user, error) in
            
            guard let mySelf = self else {return}
                if let error = error {
                    mySelf.presenter?.registerFaild(error:error)
                  
                }
                else {
                    

                    mySelf.ref.child("data/users").updateChildValues(["\(Auth.auth().currentUser!.uid)":["Email":email,"Username":username]])
                    mySelf.presenter?.regiterDoneSuccessfully()

                    
                    //At this point, the user will be taken to the next screen
                }
            } }
    
    

    weak var presenter: registerInteractorOutputProtocol?
}
