//
//  homeInteractor.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homeInteractor: homeInteractorProtocol {

    weak var presenter: homePresenterProtocol?
}
