//
//  homeProtocols.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol homeWireframeProtocol: class {
func showSearchController()
}
//MARK: Presenter -
protocol homePresenterProtocol: class {
func showSearchController()
}

//MARK: Interactor -
protocol homeInteractorProtocol: class {

  var presenter: homePresenterProtocol?  { get set }
}

//MARK: View -
protocol homeViewProtocol: class {

  var presenter: homePresenterProtocol?  { get set }
}
