//
//  homeViewController.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homeViewController: UIViewController, homeViewProtocol {

	var presenter: homePresenterProtocol?
    @IBAction func searchButtonPressed(_ sender: Any) {
        presenter?.showSearchController()
        
      
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
       // self.navigationController?.isToolbarHidden = false
     
    }
    
    
}
