//
//  homeRouter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


class homeRouter: homeWireframeProtocol {
    func showSearchController() {
          //let searchController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "\(SearchViewController.self)") as! SearchViewController
        let vc = searchRouter.createModule()
        self.viewController?.present(vc, animated: true, completion: nil)
    }
    
        
        weak var viewController: UIViewController?
        
        static func createModule() -> UIViewController {
            // Change to get view from storyboard if not using progammatic UI
            let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "\(homeViewController.self)") as! homeViewController
            let interactor = homeInteractor()
            let router = homeRouter()
            let presenter = homePresenter(interface: view, interactor: interactor, router: router)
            
            view.presenter = presenter
            interactor.presenter = presenter
            router.viewController = view
            
            return view
        }
    }
