//
//  homePresenter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homePresenter: homePresenterProtocol {
    func showSearchController() {
        router.showSearchController()
    }
    

    weak private var view: homeViewProtocol?
    var interactor: homeInteractorProtocol?
    private let router: homeWireframeProtocol

    init(interface: homeViewProtocol, interactor: homeInteractorProtocol?, router: homeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
