//
//  homeViewController.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit
class homeViewController: UIViewController, homeViewProtocol {
    
    
    @IBOutlet weak var mapView: MKMapView!
    var presenter: homePresenterProtocol?
    @IBAction func searchButtonPressed(_ sender: Any) {
        presenter?.showSearchController()
        
        
    }
    
    func setupNavBar(){
        self.navigationController?.isToolbarHidden = false
        let menu = UIBarButtonItem(image: UIImage(named: "menu"), style: .plain, target: self, action:#selector(didMenuSelected))
        self.navigationItem.leftBarButtonItem  = menu
        
        self.navigationItem.setHidesBackButton(true, animated: true);
    }
    
    @objc func didMenuSelected() {
           print("handle menu")
       }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // self.navigationController?.isToolbarHidden = false
        setupNavBar()
        mapView.addGestureRecognizer(UILongPressGestureRecognizer(target: self, action: #selector(didLongpressed(sender:))))
        
    }
    
    @objc func didLongpressed(sender: UILongPressGestureRecognizer) {
        if sender.state != UIGestureRecognizer.State.began { return }
        let touchLocation = sender.location(in: mapView)
        let locationCoordinate = mapView.convert(touchLocation, toCoordinateFrom: mapView)
        let annotation = MKPointAnnotation()
           annotation.coordinate = locationCoordinate
           mapView.addAnnotation(annotation)
        
        presenter?.showPhotosViewController(lat: locationCoordinate.latitude, long:locationCoordinate.longitude )
    }
    
    
}
