//
//  homePresenter.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class homePresenter: homePresenterProtocol {
    func showPhotosViewController(lat: Double, long: Double) {
        router.showPhotosViewController(lat: lat, long: long)
    }
    
    func showSearchController() {
        router.showSearchController()
    }
    

    weak private var view: homeViewProtocol?
    var interactor: homeInteractorProtocol?
    private let router: homeWireframeProtocol

    init(interface: homeViewProtocol, interactor: homeInteractorProtocol?, router: homeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
