//
//  homeProtocols.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol homeWireframeProtocol: class {
    func showSearchController()
    func showPhotosViewController(lat:Double , long:Double)
}
//MARK: Presenter -
protocol homePresenterProtocol: class {
    func showSearchController()
    func showPhotosViewController(lat:Double , long:Double)
}

//MARK: Interactor -
protocol homeInteractorProtocol: class {
    
    var presenter: homePresenterProtocol?  { get set }
}

//MARK: View -
protocol homeViewProtocol: class {
    
    var presenter: homePresenterProtocol?  { get set }
}
