//
//  searchRouter.swift
//  Get Photos From Location
//
//  Created by Mohamed Korany Ali on 2/11/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class searchRouter: searchWireframeProtocol {
    func showPhotosScreen(lat: Double, long: Double) {
        let vc = photosRouter.createModule() as! photosViewController
        vc.lat = lat
        vc.long = long
        self.viewController?.present(vc, animated: true, completion: nil)
    }
    
    
    weak var viewController: searchViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "\(searchViewController.self)") as! searchViewController
        let interactor = searchInteractor()
        let router = searchRouter()
        let presenter = searchPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    
   
    
    
    
}
