//
//  searchRouter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class searchRouter: searchWireframeProtocol {
    
    weak var viewController: searchViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
       let view = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "\(searchViewController.self)") as! searchViewController
        let interactor = searchInteractor()
        let router = searchRouter()
        let presenter = searchPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    
        return view
    }
    
    
    func showPhotosViewController() {
        let vc = photosRouter.createModule()
        self.viewController?.photoVCDelegate = vc as! LatLongDelegate
        
       self.viewController?.present(vc, animated: true, completion: nil)
    }
    
    
    
}
