//
//  searchInteractor.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class searchInteractor: searchInteractorProtocol {

    weak var presenter: searchPresenterProtocol?
}
