//
//  searchPresenter.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/10/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit

class searchPresenter: searchPresenterProtocol {
    func showPhotosScreen() {
        router.showPhotosViewController()
    }
    
    
     var request:MKLocalSearch.Request?
    func performSearch(text: String) {
        request = MKLocalSearch.Request()
              request?.naturalLanguageQuery = text
              
              let search = MKLocalSearch(request: request!)
              search.start { [weak self] (response, error) in
                  
                  guard self != nil else { return }
                  
                  
                  guard let response = response else {
                      return
                  }
                guard let mySelf = self else{return}
                
                mySelf.view?.updateMapItems(items: response.mapItems)
               
    }
    }
   
    

    weak private var view: searchViewProtocol?
    var interactor: searchInteractorProtocol?
    private let router: searchWireframeProtocol

    init(interface: searchViewProtocol, interactor: searchInteractorProtocol?, router: searchWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
