//
//  loginViewController.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/9/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

import AnAlertView

enum ValidationError: Error {
    case tooShort
    case tooLong
    case invalidCharacterFound(Character)
    
}



class loginViewController: UIViewController , AlertViewDelegate  {
  
    
    var presenter: loginPresenterProtocol?
    
    
   
    
    func dismissButtonTapped(_ button: UIButton) {
        self.username.text = ""
        self.password.text = ""
    }
    
    @IBOutlet weak var username: DesignableUITextField!
    
    @IBOutlet weak var password: DesignableUITextField!
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        let customColor = UIColor.white
        username.layer.borderColor = customColor.cgColor
        password.layer.borderColor = customColor.cgColor
        
        username.layer.borderWidth = 1.0
        password.layer.borderWidth = 1.0
       
    }
    
    
    @IBAction func didSignUpPressed(_ sender: Any) {
        presenter?.showRegisterPage()
    }
    
    @IBAction func didLoginPressed(_ sender: Any) {
        
        guard let user = self.username.text else { return  }
                   guard let pass = self.password.text else { return  }
        do {
           
            try self.validate(username: user ) {
                print($0)
                
            }

           } catch {

            AlertView.showAlert(message: error.localizedDescription, button: "ok", delegate: self, container: self, image: UIImage(named: "warning"))
            return
           }
        
        presenter?.handeLogin(username:user , password: pass)
        
        
    }
    
 
    func validate(username: String,then handler: @escaping (ValidationError?) -> Void) throws {
        guard username.count > 3 else {
            throw ValidationError.tooShort
        }
        
        guard username.count < 25 else {
            throw ValidationError.tooLong
        }
        
//        for character in username {
//            guard character.isLetter else {
//                throw ValidationError.invalidCharacterFound(character)
//            }
//        }
    }

}






extension ValidationError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .tooShort:
            return NSLocalizedString(
                "Your username needs to be at least 4 characters long",
                comment: ""
            )
        case .tooLong:
            return NSLocalizedString(
                "Your username can't be longer than 24 characters",
                comment: ""
            )
        case .invalidCharacterFound(let character):
            let format = NSLocalizedString(
                "Your username can't contain the character '%@'",
                comment: ""
            )

            return String(format: format, String(character))
        }
    }
}
