//
//  loginInteractor.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/9/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import FirebaseAuth

class loginInteractor: loginInteractorInputProtocol {
    func handleLogin(username: String, password: String) {
        Auth.auth().signIn(withEmail: username, password: password) { [weak self] (user, error) in
            
           
            
            if let error = error {
                self?.presenter?.loginFaild(error:error)
                return
            }
                     
            self?.presenter?.loginDoneSuccessfully()
        }
    }
    

    weak var presenter: loginInteractorOutputProtocol?
}
