//
//  loginProtocols.swift
//  Get Photos By Location
//
//  Created Mohamed Korany Ali on 2/9/20.
//  Copyright © 2020 Mohamed Korany Ali. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol loginWireframeProtocol: class {

    func showHomeScreen()
    func showSignUpScreen()
}
//MARK: Presenter -
protocol loginPresenterProtocol: class {

    var interactor: loginInteractorInputProtocol? { get set }
    func handeLogin(username:String ,password : String)
    func showRegisterPage()
    
}

//MARK: Interactor -
protocol loginInteractorOutputProtocol: class {

    func loginDoneSuccessfully()
    func loginFaild(error:Error)
    
    
    /* Interactor -> Presenter */
}

protocol loginInteractorInputProtocol: class {

    var presenter: loginInteractorOutputProtocol?  { get set }
    func handleLogin(username:String , password:String)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol loginViewProtocol: class {

    var presenter: loginPresenterProtocol?  { get set }
    func showIndicator()
    func hideIndicator()
    func showErrorAlert(error:String)

    /* Presenter -> ViewController */
}
